name = "backend-cloudflare-poc"
main = "src/index.ts"
compatibility_date = "2024-11-27"

# Required for mysql2 compatibility
compatibility_flags = ["nodejs_compat"]

# Hyperdrive 绑定配置
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "a319d11c28c74d2598fc4c2939ba470a"

# 开发环境配置
[dev]
port = 8787
